name: API Tests

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Node.js (для allure-commandline)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Allure Commandline (npm)
      run: npm install -g allure-commandline

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run tests with Allure
      run: pytest --alluredir=allure-results --env=dev

    - name: Generate Allure report
      run: allure generate allure-results -o allure-report --clean

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report

